theme: jekyll-theme-cayman
title: Mini-curso 04 — Display TFT com MicroPython
description: Mini-curso de Sistemas Embarcados — Display TFT (ST7735) com MicroPython, ESP32 e Raspberry Pi Pico
show_downloads: false
